### ISSUE TITLE
초기 작업

### ISSUE THREAD

**Issue by sunnyineverywhere** [KUBER-LOUDY/scuba#1]
- [x] 피그마 정리(화면에 뭐가들어갈지 정도)
- [x] go에서 서버 모듈 어떻게 구조 짜는지 => 적용
- [x] Unix 소켓을 활용하는 형태가 우분투에서 동작하는지
- [x] API 문서 정독(https://docs.docker.com/engine/api/v1.43/#section/Authentication)
- [ ] Exec 명령어로 접속하는 것도 api로 어디까지 가능한지

**Comment by yhjune** [comment]
[figma veiw](https://www.figma.com/file/VHvfJi2IosxXQQcsUSKPKR/SKT-FellowShip?type=design&node-id=70-159&mode=design)

**Comment by yhjune** [comment]
[go server desgin](https://www.mobiinside.co.kr/2018/03/02/buzzvil-go-server/)
[build server with go](https://dev.to/aniket762/build-server-with-go-under-10-minutes-1i9m)
